version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - website_files:/var/www/
    networks:
      - docker_network
    ports:
      - "443:443"
  # wordpress:
  #   build: ./requirements/wordpress
  #   container_name: wordpress
  #   networks:
  #     - docker_network
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - docker_network
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always

volumes:
  database:
  website_files:

networks:
  docker_network:
    driver: bridge